Added RHS support to gilab plugin.
Brightscout/mattermost-plugin-gitlab pull request #1
Opened 2022-05-25 13:39 UTC by raghavaggarwal2308

1. Displaying RHS onclick of LHS buttons.
2. Displaying users merge requests, assignments, unreads and reviews in RHS.
3. Displaying labels on merge requests, assignments and reviews

![gitlabMergeRequests](https://user-images.githubusercontent.com/55234496/170275761-75bab340-4e6c-476a-9040-474378c76a8a.png)

![gitlabUnreads](https://user-images.githubusercontent.com/55234496/170275193-c587a71b-5c5a-4c9e-81c9-969d52e522c6.png)

![gitlabReviews](https://user-images.githubusercontent.com/55234496/170275178-dd5d0c8a-68bb-40ed-aaa3-c4f4f602587a.png)

![gitlabAssignments](https://user-images.githubusercontent.com/55234496/170275139-b2d855ce-8c70-4e30-adaa-63173803a9da.png)
.

2022-05-26 05:40 UTC, raghavaggarwal2308 commented on webapp/package.json
> +        "react": "16.14.0",
I was setting up the project to use typescript. I guess upgraded by mistake while doing that.

2022-05-26 06:17 UTC, raghavaggarwal2308 commented on webapp/package.json
> +        "typescript": "4.6.4"
"ts-standard" was extra removed it.
"typescript" is for using typescript in the project.

2022-05-30 06:20 UTC, raghavaggarwal2308 commented on webapp/package.json
> +        "react": "16.14.0",
I was setting up the project to use typescript, I guess upgraded by mistake while doing that.

2022-05-30 06:21 UTC, raghavaggarwal2308 commented on webapp/package.json
> +        "typescript": "4.6.4"
"ts-standard" was extra removed it.
"typescript" is for using typescript in the project.

2022-05-30 07:37 UTC, manojmalik20 requested changes

2022-05-30 07:37 UTC, manojmalik20 commented on webapp/src/actions/index.js
> +            getState,
Revert this change.

2022-05-31 05:53 UTC, raghavaggarwal2308 commented on webapp/src/components/sidebar_header/sidebar_header.jsx
> +  static propTypes = {
no i have not changed any rules. It was passed by check-style earlier. Now its fixed. Maybe because of eslint version.

2022-06-01 17:42 UTC, manojmalik20 requested changes

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +  return items.length > 0 ? (
```suggestion
  return items.length ? (
```

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +      }
```suggestion
      const repoName = item.references?.full ?? item.project?.path_with_namespace ?? '';
```

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +      }
```suggestion
      const userName = item.author?.username ?? '';
```

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +            {'#' + item.iid}
```suggestion
            {`#${item.iid}`}
```

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +      }
Use the `??` operator here.

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +            href={item.web_url || item.target_url}
```suggestion
            href={item.web_url ?? item.target_url}
```

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +      if (item.milestone) {
Use ternary operator here.

2022-06-01 17:42 UTC, manojmalik20 commented on webapp/src/components/sidebar_right/gitlab_items.tsx
> +            <span className='light'>{'(' + repoName + ')'}</span>
```suggestion
            <span className='light'>{`(${repoName})`}</span>
```

2022-06-02 05:07 UTC, avas27JTG commented on webapp/src/utils/styles.js
> +            // Removes weird border around container
```suggestion
            // Removes border around container
```

2022-06-02 05:07 UTC, avas27JTG commented on webapp/src/utils/styles.js
> +            // Overwrittes the different states of border
```suggestion
            // Overwrites the different states of border
```

2022-06-02 05:07 UTC, avas27JTG commented on webapp/src/utils/styles.js
> +            fontSize: '90%',
prevent using `%` for font-size try `px, em, rem`

2022-06-02 05:07 UTC, avas27JTG commented on webapp/src/utils/styles.js
> +    return 'rgb(' + r + ', ' + g + ', ' + b + ')';
```suggestion
   const rgb = `${r}, ${g}, ${b}`;
   return alpha ? `rgba(${rgb}, ${alpha})` : `rgb(${rgb})`;
```

2022-06-02 05:07 UTC, avas27JTG commented on webapp/src/utils/styles.js
> +    return (yiq >= 128) ? 'black' : 'white';
if you are trying to pass color from here then use hex code `#ffffff` for white and `#000000` for black

remember always try using only `hex` or `rgb, rgba` color codes on the website for better compatibility

2022-06-02 05:07 UTC, avas27JTG commented
@raghavaggarwal2308 
try writing the description in simple present tense

```
Display RHS onclick of LHS buttons.
Display users merge requests, assignments, unreads and reviews in RHS.
Display labels on merge requests, assignments and reviews.
```

2022-06-03 12:36 UTC, manojmalik20 requested changes

2022-06-03 12:36 UTC, manojmalik20 commented on webapp/src/types/gitlab_items.tsx
> +  }
Add EOF.

2022-06-03 12:36 UTC, manojmalik20 commented on webapp/src/utils/date_utils.js
> +        return `${secondsSince} ${secondsSince === 1 ? ' second' : ' seconds'}`;
```suggestion
        return `${secondsSince} ${secondsSince === 1 ? 'second' : 'seconds'}`;
```

2022-06-03 12:36 UTC, manojmalik20 commented on webapp/src/utils/date_utils.js
> +        return `${minutesSince} ${minutesSince === 1 ? ' minute' : ' minutes'}`;
```suggestion
        return `${minutesSince} ${minutesSince === 1 ? 'minute' : 'minutes'}`;
```

2022-06-03 12:36 UTC, manojmalik20 commented on webapp/src/utils/date_utils.js
> +        return `${hoursSince} ${hoursSince === 1 ? ' huor' : ' hourss'}`;
```suggestion
        return `${hoursSince} ${hoursSince === 1 ? 'hour' : 'hours'}`;
```

2022-06-03 12:36 UTC, manojmalik20 commented on webapp/src/utils/date_utils.js
> +    return `${daysSince} ${daysSince === 1 ? ' day' : ' days'}`;
```suggestion
    return `${daysSince} ${daysSince === 1 ? 'day' : 'days'}`;
```

2022-06-03 15:35 UTC, manojmalik20 commented on webapp/babel.config.js
> +        '@babel/plugin-proposal-nullish-coalescing-operator',
Discussed.

2022-06-03 16:46 UTC, manojmalik20 approved these changes

2022-06-03 16:48 UTC, merged