[MI-2701]: Done the review fixes of a PR: Adding create issue modal #306
Brightscout/mattermost-plugin-gitlab pull request #28
Opened 2023-02-01 12:22 UTC by Nityanand13

PR: [#306](https://github.com/mattermost/mattermost-plugin-gitlab/pull/306)

2023-02-01 13:18 UTC, raghavaggarwal2308 requested changes

2023-02-01 13:18 UTC, raghavaggarwal2308 commented on webapp/src/images/icons/gitlab.tsx
> +    const iconStyle = type === 'menu' ? {flex: '0 0 auto', width: '20px', height: '20px', borderRadius: '50px', padding: '2px', filter: 'invert(74%) sepia(31%) saturate(2094%) hue-rotate(339deg) brig
Use the actual Gitlab icon

2023-02-03 11:24 UTC, raghavaggarwal2308 approved these changes

2023-02-03 13:33 UTC, manojmalik20 approved these changes

2023-02-03 13:38 UTC, merged