[MI 2837]: Done the review fixes of a gitlab PR #301
Brightscout/mattermost-plugin-gitlab pull request #30
Opened 2023-03-15 12:44 UTC by Nityanand13

[PR: #301](https://github.com/mattermost/mattermost-plugin-gitlab/pull/301)

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/package-lock.json
These changes should not be here

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +
```suggestion
export const  getInfoAboutLink = (href, hostname) => {
    return href.split(`${hostname}/`)[1].split('/');
}

```

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +
Check if this works

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +        return null
```suggestion
        return null;
```

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                                See more
```suggestion
                                {'See more'}
```

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                                See more
Please check eslint configuration

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.test.jsx
> +    it("should return the correct owner, repo, type, and number when given a valid GitLab href and hostname with all required information", () => {
```suggestion
    it("Should return the correct owner, repo, type, and number when given a valid GitLab href and hostname with all required information", () => {
```

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/components/link_tooltip/link_tooltip.test.jsx
> +    it("should return the correct owner, repo, type, and number when given a valid GitLab href and hostname with all required information", () => {
Check everywhere

2023-03-21 06:38 UTC, SaurabhSharma-884 commented on webapp/src/utils/regex_utils.test.js
> +describe("validateGitlabURL", () => {
Can add a descriptive statement here instead of `validateGitlabURL`

2023-03-29 07:02 UTC, Nityanand13 commented on webapp/package-lock.json
@SaurabhSharma-884 Is there any specific reason behind that?

2023-03-29 07:22 UTC, SaurabhSharma-884 commented on webapp/package-lock.json
This is auto-generated when we run `npm install` also it may give rise to lots of conflicts while merging or rebasing.

2023-03-29 07:22 UTC, SaurabhSharma-884 approved these changes

2023-03-29 07:26 UTC, Nityanand13 commented on webapp/package-lock.json
@SaurabhSharma-884 There are a few new packages that I installed due to which it is auto-generated.

2023-03-29 07:36 UTC, sooraj-shukla requested changes

2023-03-29 07:36 UTC, sooraj-shukla commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                                        <span style={{color: label.text_color}}>{label.name}</span>
Avoid inline styles.

2023-03-29 07:36 UTC, sooraj-shukla commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                                        key={index}
Avoid using `index` as key.

2023-03-29 07:36 UTC, sooraj-shukla commented on webapp/package.json
>      }
Keep the jest config in a separate `jest.config.(js|ts|....)` file instead of adding it in `package.json` file.

2023-03-29 07:54 UTC, Nityanand13 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                                        <span style={{color: label.text_color}}>{label.name}</span>
Discussed

2023-03-29 09:35 UTC, sooraj-shukla approved these changes

2023-03-30 09:30 UTC, avas27JTG commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                    {/* info */}
remove it or if there is a need to explain anything add descriptive comment

2023-03-30 09:30 UTC, avas27JTG commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                        {/* base <- head */}
same as above

2023-03-30 12:55 UTC, avas27JTG approved these changes

2023-03-30 13:12 UTC, raghavaggarwal2308 approved these changes

2023-03-30 13:14 UTC, merged