[MI-2963]: Did the review fixes of gitlab PR #301
Brightscout/mattermost-plugin-gitlab pull request #32
Opened 2023-04-04 07:37 UTC by Nityanand13

[PR: #301](https://github.com/mattermost/mattermost-plugin-gitlab/pull/301)

2023-04-04 11:20 UTC, raghavaggarwal2308 requested changes
Look at [this comment](https://github.com/mattermost/mattermost-plugin-gitlab/pull/301#discussion_r1153737570) as well.

In the default case just log a message example: "this link type is not supported" and break from the switch case

2023-04-04 11:20 UTC, raghavaggarwal2308 commented on webapp/src/components/link_tooltip/link_tooltip.test.jsx
> +    it('Should return an object invalid owner, repo, type, and number when given a valid hostname and invalid href', () => {
Add a testcase for issue comment as well as mentioned in the [comment](https://github.com/mattermost/mattermost-plugin-gitlab/pull/301#discussion_r1153742764)

2023-04-05 11:35 UTC, raghavaggarwal2308 requested changes

2023-04-05 11:35 UTC, raghavaggarwal2308 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +    return {
Add a check if length is greater than or equal to 5

2023-04-05 11:35 UTC, raghavaggarwal2308 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +            dispatch(logError('this link type is not supported'));
```suggestion
            dispatch(logError('this link type is not supported to display a tooltip'));
```

2023-04-05 11:35 UTC, raghavaggarwal2308 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
>                      break;
add the default case here as well

2023-04-05 12:46 UTC, Kshitij-Katiyar commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                    dispatch(logError('this link type is not supported to display a tooltip'));
make this warn

2023-04-05 12:46 UTC, Kshitij-Katiyar commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +            dispatch(logError('this link type is not supported to display a tooltip'));
same

2023-04-05 12:46 UTC, Kshitij-Katiyar commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +            dispatch(logError('this link type is not supported to display a tooltip'));
do something like and see if this work or explore
```suggestion
            dispatch(logError('link type %s is not supported to display a tooltip ',data.type) );
```

2023-04-05 12:46 UTC, Kshitij-Katiyar commented on webapp/src/components/link_tooltip/link_tooltip.test.jsx
> +    it('Should return an empty object when given a valid GitLab hostname and href missing the type', () => {
Should return an empty object when given a valid GitLab hostname and href with missing the type parameter

2023-04-05 12:58 UTC, Nityanand13 commented on webapp/src/components/link_tooltip/link_tooltip.jsx
> +                    dispatch(logError('this link type is not supported to display a tooltip'));
Discussed

2023-04-05 13:00 UTC, Kshitij-Katiyar commented on webapp/src/components/link_tooltip/link_tooltip.test.jsx
> +    it('Should return an empty object when given a valid hostname and invalid href', () => {
```suggestion
    it('Should return an empty object when given a valid hostname and a invalid href', () => {
```

2023-04-05 13:06 UTC, merged