[MM-387]: Added support to subscribe to release and deployment
Brightscout/mattermost-plugin-gitlab pull request #46
Opened 2024-07-29 14:37 UTC by Kshitij-Katiyar

### Description
Added support to subscribe to release and deployment.

### Screenshots
![image](https://github.com/user-attachments/assets/01e27a55-c1e4-47d8-87d7-78b294dc0b13)

### What to Test
- create a subscription with release and deployment features and test the expected notifications are received.

2024-08-06 09:43 UTC, raghavaggarwal2308 requested changes

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	repo := event.Project
```suggestion
	project := event.Project
```

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	}
```suggestion
	}
	
```

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	}
```suggestion
	}
	
```

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	)
```suggestion
	subs := w.gitlabRetreiver.GetSubscribedChannelsForProject(
		ctx, namespaceMetadata.Namespace,
		namespaceMetadata.Project,
		repo.VisibilityLevel == PublicVisibilityLevel,
	)
```

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	}
```suggestion
	}
	
```

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/deployment.go
> +	switch event.Status {
Add a screenshot for each type of event we are receiving in the description

2024-08-06 09:43 UTC, raghavaggarwal2308 commented on server/webhook/release.go
> +	message := fmt.Sprintf("### Release: **%s**\n", event.Action)
Dont you think it will be better to use a slack attachment here instead of markdown?

2024-08-06 17:36 UTC, raghavaggarwal2308 commented on server/webhook/release.go
> +	release := event.Project
Shouldnt this be project?

2024-08-06 17:42 UTC, raghavaggarwal2308 commented
Also, fix the failing lint

2024-08-07 08:36 UTC, Kshitij-Katiyar commented
Created a PR with all the changes in the Mattermost organization's GitLab plugin repo, so closing this one

2024-08-07 08:36 UTC, closed without merging