Add "Attach comment to issue" modal
Brightscout/mattermost-plugin-gitlab pull request #8
Opened 2022-06-14 04:45 UTC by raghavaggarwal2308

1. Create button to open "Attach comment" modal in context menu.
2. Create modal to attach comment.
3. Create API to create issue comment & search issue.
4. Create notification post when comment is attached.

2022-06-14 07:01 UTC, Kshitij-Katiyar requested changes

2022-06-14 08:03 UTC, raghavaggarwal2308 commented on server/gitlab/api.go
> +	if err != nil {
We are checking for the status code of the response in respErr (ie if its 404 or 403).

2022-06-15 04:54 UTC, raghavaggarwal2308 commented on webapp/src/components/attach_comment_to_issue_menu/attach_comment_to_issue.jsx
> +        postId: PropTypes.string,
its coming in the props with this name.

2022-06-16 18:32 UTC, Kshitij-Katiyar requested changes

2022-06-17 10:31 UTC, raghavaggarwal2308 commented on server/plugin.go
> +		if err.ID != APIErrorIDNotConnected {
its a constant already declared in plugin package.....returned by "getGitlabUserInfoByMattermostID" if user is not connected.

2022-06-17 19:44 UTC, raghavaggarwal2308 commented
Fixes of this PR are in the following PR-

https://github.com/Brightscout/mattermost-plugin-gitlab/pull/10

2022-06-17 19:44 UTC, closed without merging